document.write('<div class="footer">');
document.write('<div class="bb"></div><!-- separator div -->');
document.write('<script type="text/javascript" src="js/tl.js"></script>');
document.write('<div class="footer_content">');
document.write('<div class="footer_square">');
document.write('<div style="width:100%;text-align:left;">[ Redes ]</div>');
document.write('<div class="xb"></div>');
document.write('<ul>');
document.write('<li><a href="http://facebook.com/ricardoherrerablancas">Facebook</a></li>');
document.write('<li><a href="http://twitter.com/#!/nostroke">Twitter</a></li>');
document.write('<li><a href="http://www.linkedin.com/">LinkedIn</a></li>');
document.write('<li><a href="http://nostroke.deviantart.com">deviantART</a></li>');
document.write('<li><a href="http://answers.yahoo.com/activity?show=K427VYKbaa">Yahoo Respuestas</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('<div class="footer_square">');
document.write('<div style="width:100%;text-align:left;">[ Enlaces ]</div>');
document.write('<div class="xb"></div>');
document.write('<p style="text-align:justify;"><a href="http://www.xatakaciencia.com" style="font-size:14px;text-decoration:none;">ciencia</a> ');
document.write('<a href="http://www.snipplr.com" style="font-size:13px;text-decoration:none;">programaci&oacute;n</a> ');
document.write('<a href="http://www.gizmodo.com" style="font-size:17px;text-decoration:none;">tecnolog&iacute;a</a> ');
document.write('<a href="http://www.itunes.com" style="font-size:20px;text-decoration:none;">m&uacute;sica</a> ');
document.write('<a href="http://www.identidadgeek.com" style="font-size:16px;text-decoration:none;">curiosidades</a> ');
document.write('<a href="http://www.mensfitness.com" style="font-size:12px;text-decoration:none;">salud</a> ');
document.write('<a href="http://www.lossimpsononline.com.ar" style="font-size:16px;text-decoration:none;">entretenimiento</a> ');
document.write('<a href="http://www.cnn.com" style="font-size:18px;text-decoration:none;">actualidad</a> ');
document.write('<a href="http://www.apple.com" style="font-size:14px;text-decoration:none;">Innovaci&oacute;n</a> ');
document.write('<a href="http://www.deviantart.com" style="font-size:16px;text-decoration:none;">dise&ntilde;o</a> ');
document.write('<a href="http://www.secondlife.com" style="font-size:15px;text-decoration:none;">3D</a> ');
document.write('<a href="http://www.kirupa.com" style="font-size:12px;text-decoration:none;">procesos</a> ');
document.write('<a href="http://www.howstuffworks.com" style="font-size:16px;text-decoration:none;">respuestas</a> ');
document.write('<a href="http://www.wikipedia.com" style="font-size:15px;text-decoration:none;">estudio</a> ');
document.write('<a href="http://www.adobe.com" style="font-size:11px;text-decoration:none;">entornos de desarrollo</a></p>');
document.write('</div>');
document.write('<div class="footer_square">');
document.write('<div style="width:100%;text-align:left;">[ Contacto ]</div>');
document.write('<div class="xb"></div>');
document.write('<div style="font-size:13px;line-height:145px;text-align:center;">');
document.write('E-Mail: &#114;<!-- @. -->&#105;<!-- @. -->&#099;<!-- @. -->&#097;<!-- @. -->&#114;<!-- @. -->&#100;<!-- @. -->&#111;<!-- @. -->&#104;<!-- @. -->&#098;<!-- @. -->&#064;<!-- @. -->&#109;<!-- @. -->&#101;<!-- @. -->&#046;<!-- @. -->&#099;<!-- @. -->&#111;<!-- @. -->&#109;');
document.write('</div>');
document.write('</div>');
document.write('<div class="clear"></div>');
document.write('</div>');
document.write('<div class="copyright">&copy; Ricardo H. B.  - Dise&ntilde;o y Desarrollo | [ &#114;<!-- @. -->&#105;<!-- @. -->&#099;<!-- @. -->&#097;<!-- @. -->&#114;<!-- @. -->&#100;<!-- @. -->&#111;<!-- @. -->&#104;<!-- @. -->&#098;<!-- @. -->&#064;<!-- @. -->&#109;<!-- @. -->&#101;<!-- @. -->&#046;<!-- @. -->&#099;<!-- @. -->&#111;<!-- @. -->&#109; ] | Nombres, im&aacute;genes y logotipos son propiedad de sus respectivas marcas &reg; | 2011 - 2012 M&eacute;xico D.F.</div>');