document.write('<div id="timeline_wrapper">');
document.write('<div id="timeline">');
document.write('<ul>');
document.write('<li class="Sesi&oacute;n: PHP - OOP" title="Sat Nov 5 2011">Introducci&oacute;n a la programaci&oacute;n orientada a objetos en PHP.</li>');
document.write('<li class="Sesi&oacute;n: Apps" title="Sat Nov 12 2011">M&eacute;todos para programaci&oacute;n de aplicaciones grandes y un vistazo al simulador de maquillaje.</li>');
document.write('<li class="Update de la secci&oacute;n proyectos" title="Mon Nov 18 2011">Nuevos proyectos y art&iacute;culos.</li>');
document.write('<li class="Sesi&oacute;n de estudio cancelada" title="Sat Nov 19 2011">Debido a un compromiso previo el s&aacute;bado 19 no habr&aacute; sesi&oacute;n de estudio.</li>');
document.write('<li class="Sesi&oacute;n: PHP - OOP" title="Sat Nov 26 2011">Continuamos con la programaci&oacute;n orientada a objetos en PHP.</li>');
document.write('<li class="Tomi cumple a&ntilde;os!" title="Mon Nov 28 2011">14 a&ntilde;os alegr&aacute;ndonos la vida. Gracias chica!</li>');
document.write('<li class="Mi cumplea&ntilde;os :-)" title="Fri Dec 2 2011">Se aceptan obsequios y felicitaciones.</li>');
document.write('<li class="Sesi&oacute;n de estudio cancelada" title="Sat Dec 3 2011">Debido a un compromiso previo el s&aacute;bado 3 no habr&aacute; sesi&oacute;n de estudio.</li>');
document.write('<li class="Sesi&oacute;n: Desarrollo de apps para m&oacute;viles" title="Sat Dec 10 2011">Introducci&oacute;n al desarrollo de apps para dispositivos; iPhone, iPad y iPod touch.</li>');
document.write('<li class="Recordando a la Virgen de Guadalupe y a mi segunda madrecita" title="Mon Dec 12 2011">Anita nos haces falta y te extra&ntilde;amos, nunca vamos a olvidarte.</li>');
document.write('<li class="Sesi&oacute;n: PHP - OOP" title="Sat Dec 10 2011">Programaci&oacute;n de una clase para gestionar una conexi&oacute;n a base de datos.</li>');
document.write('<li class="Sesi&oacute;n: Dise&ntilde;o de interfaces gr&aacute;ficas; m&eacute;todos y requerimientos" title="Sat Dec 17 2011">Construcci&oacute;n de una interfaz animada para el proyecto Biblioteca Vasconcelos.</li>');
document.write('<li class="Nochebuena; no habr&aacute; sesi&oacute;n de estudio" title="Sat Dec 24 2011">Que disfruten la compa&ntilde;&iacute;a de sus familiares y allegados.</li>');
document.write('<li class="Navidad; &iquest;Qu&eacute; les han regalado?" title="Sun Dec 25 2011">Cuenten, nos vemos en facebook.</li>');
document.write('<li class="V&iacute;spera de a&ntilde;o nuevo" title="Sat Dec 31 2011">Repasando el 2011, en general un a&ntilde;o bastante dif&iacute;cil.</li>');
document.write('<li class="Nuevo a&ntilde;o, nuevos retos" title="Sun Jan 1 2012">Los mejores deseos para todos y comencemos con el pie derecho.</li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');